#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

const projectRoot = path.resolve(import.meta.dirname, "..");
const environmentPath = path.join(projectRoot, ".env.local");
const dataDirectory = path.join(projectRoot, "server-data", "boards");
const skipInstall = process.argv.includes("--skip-install");

function secret(bytes = 24) {
  return randomBytes(bytes).toString("base64url");
}

function parseEnvironment(source) {
  const values = new Map();
  for (const line of source.split(/\r?\n/)) {
    const match = line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/);
    if (match) values.set(match[1], match[2]);
  }
  return values;
}

const majorVersion = Number.parseInt(process.versions.node.split(".")[0], 10);
if (!Number.isFinite(majorVersion) || majorVersion < 22) {
  console.error(`OBSdraw requires Node.js 22 or newer. Current version: ${process.version}`);
  process.exit(1);
}

await mkdir(dataDirectory, { recursive: true });

let existing = "";
try {
  existing = await readFile(environmentPath, "utf8");
} catch (error) {
  if (error?.code !== "ENOENT") throw error;
}

const values = parseEnvironment(existing);
const defaults = new Map([
  ["ACCESS_KEY", secret(18)],
  ["VIEW_KEY", secret(18)],
  ["AUTH_SECRET", secret(48)],
  ["SOCKET_AUTH_SECRET", secret(48)],
  ["LOCAL_STORE_DIR", "./server-data"],
  ["NEXT_PUBLIC_SOURCE_URL", "https://github.com/malithedeveloper/obsdraw"],
]);

const additions = [];
for (const [key, value] of defaults) {
  if (!values.has(key)) {
    values.set(key, value);
    additions.push(`${key}=${value}`);
  }
}

if (additions.length) {
  const separator = existing && !existing.endsWith("\n") ? "\n" : "";
  const heading = existing ? "\n# Added by npm run setup\n" : "# Generated by npm run setup\n";
  await writeFile(environmentPath, `${existing}${separator}${heading}${additions.join("\n")}\n`, {
    mode: 0o600,
  });
}
await chmod(environmentPath, 0o600);

if (!skipInstall) {
  const npmCommand = process.platform === "win32" ? "npm.cmd" : "npm";
  console.log("Installing dependencies…");
  const install = spawnSync(npmCommand, ["install", "--no-fund", "--no-audit"], {
    cwd: projectRoot,
    stdio: "inherit",
  });
  if (install.status !== 0) process.exit(install.status ?? 1);
}

console.log("\nOBSdraw is ready.");
console.log(`Editor: http://localhost:3000/`);
console.log(`Access key: ${values.get("ACCESS_KEY")}`);
console.log(`OBS browser source: http://localhost:3000/view/${encodeURIComponent(values.get("VIEW_KEY") || "")}`);
console.log("Start the app with: npm run dev");
